## Adam Pithenwala

16/01/2022

In [2]:
import numpy as np

In [3]:
print(np.ceil(np.sqrt(57)))

8.0


In [4]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version

In [5]:
print(np.amin([1,4,2,6,8,9]))

1


In [6]:
print(np.amax([1,4,2,6,8,9]))

9


In [7]:
print(np.ceil(np.sum(np.sqrt([8,12,16]))))

11.0


In [8]:
x = np.array([2,4,8,10])
y = np.asarray(x)

In [9]:
print(y)

[ 2  4  8 10]


In [10]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [11]:
mat = np.array(my_mat)
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
print(mat.ndim)

2


In [13]:
print(mat.size)

9


In [14]:
print(mat.shape)

(3, 3)


In [15]:
print(mat.dtype)

int64


In [16]:
list(range(2,10,2))

[2, 4, 6, 8]

In [17]:
list(range(2,10.5,2.4))

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
np.arange(2,10.5,2.4)

array([2. , 4.4, 6.8, 9.2])

In [ ]:
np.linspace(10,40,5,endpoint=False,retstep=True)

(array([10., 16., 22., 28., 34.]), 6.0)

In [ ]:
np.random.seed(6)
print(np.random.rand(10,6))

[[0.89286015 0.33197981 0.82122912 0.04169663 0.10765668 0.59505206]
 [0.52981736 0.41880743 0.33540785 0.62251943 0.43814143 0.73588211]
 [0.51803641 0.5788586  0.6453551  0.99022427 0.8198582  0.41320093]
 [0.87626766 0.82375943 0.05447451 0.71863724 0.80217056 0.73640664]
 [0.70913175 0.54093685 0.12482417 0.9576473  0.4032563  0.21695116]
 [0.71727585 0.99420744 0.25561406 0.67130943 0.59900591 0.71733215]
 [0.93734953 0.35180977 0.2536341  0.40247251 0.74651072 0.72407057]
 [0.4061078  0.98937985 0.45049928 0.37380843 0.70962861 0.08245855]
 [0.39837292 0.77088097 0.76475098 0.28385938 0.18954219 0.47125096]
 [0.33480604 0.73473504 0.18910712 0.33110407 0.84422842 0.61502403]]


In [ ]:
print(np.random.randn(10,3))

[[-0.37550472  0.39636757 -0.47144628]
 [ 2.33660781  1.50278553 -0.59545972]
 [ 0.52834106  0.9398248   0.42628539]
 [-0.75815703 -0.16236698  0.72680996]
 [ 0.44408297 -0.85682264  0.44692842]
 [-1.01464799 -2.1323234   0.17386307]
 [ 0.95120126  0.44189739  1.46901739]
 [ 1.74951635  0.35353062 -0.64333729]
 [-0.04723705 -1.44903979 -0.03618977]
 [-0.09084699  0.17629034  1.09462041]]


In [ ]:
print(np.random.randint(10,3))

ValueError: low >= high

In [ ]:
print(np.random)

<module 'numpy.random' from '/home/adam/.local/lib/python3.11/site-packages/numpy/random/__init__.py'>


In [ ]:
print(np.random.randint(1111,9999))

6288


In [ ]:
y = np.random.randint(1111,9999)
print(y)
x = input()
if (x==y) :
    print("login successful")
else :
    while (x!=y) :
        print("Enter again")
        x = input()

In [ ]:
a = np.random.randint(1,99,30)
c = a.reshape(6,5)
print(c)


[[30 15 22 32 49]
 [ 6 71 50 26 53]
 [52 34 29 12 46]
 [83 24 10 39 92]
 [11 32 29 58 80]
 [58 80 93 84 69]]


In [ ]:
print(c.min())
np.mean(c)

6


45.63333333333333

In [ ]:
m = np.random.randint(1,100,25)
l = m.reshape(5,5)

In [ ]:
np.sort(l)

array([[13, 33, 39, 52, 55],
       [41, 42, 43, 76, 82],
       [28, 70, 76, 90, 92],
       [ 2,  4, 32, 88, 92],
       [ 7,  9, 24, 53, 93]])

In [ ]:
np.sort(l,axis=0)

array([[24, 32,  2,  9,  4],
       [42, 33, 28, 39,  7],
       [52, 41, 43, 76, 13],
       [70, 53, 55, 92, 76],
       [88, 90, 93, 92, 82]])